### ISSUE TITLE
Check language on globally unique ID's and update if necessary

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#103]
There are some changes about id's in https://github.com/radiantearth/stac-spec/pull/883 

We should be sure the API reflects that id's need to aim to be globally unique.

**Comment by jisantuc** [comment]
For Franklin (and, I don't know the database models, but I'm assuming arturo-stac-api as well), collection IDs and item IDs must be unique within the API instance -- this constraint is because we're using the item / collection IDs as table primary keys in Postgres. I don't know anything about what elasticsearch backed APIs require though.

**Comment by matthewhanson** [comment]
In the old sat-api there was an Elasticsearch index for `collections` and one for `items`, so Item IDs needed to be unique across everything.

With  the `sentinel-s2-l1a-cogs` dataset we maintain a collection for both the original L2A data, and the COG converted one. I realized that I really didn't want to change the IDs of every item, I wanted the Item IDs to be the same regardless of if it was the original JP2K data or the COG version.

 So in the current version of stac-server, there is an elasticsearch index for `collections`, and then an index exists for each collection to store those items.

**Comment by philvarner** [comment]
Should we be saying that IDs ideally are globally unique, or only that the (collectionId, itemId) tuple is globally unique?

**Comment by matthewhanson** [comment]
(collectionId, itemId) is globally unique.  I don't think we should say IDs are ideally globally unique, I don't see any reason for that.
