### ISSUE TITLE
Align Sorting with OGC API

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#16]
We should align with OGC API, and hopefully nudge them in the direction we've picked thus far. Issue: https://github.com/opengeospatial/ogcapi-records/issues/22

**Comment by m-mohr** [comment]
Just received from Carl Reed via ogc-api-records mailing list and adding here for future reference:

> Hi -
> 
> WRT the "sort" discussion. I just took a look at both SQL - sort and OpenSearch - Sort. While they use a different keyword (SQL > - Order By, OpenSearch - Sort), they do both use the same modifiers ASC|DESCand both provide the same single column or multi-column functionality.
> 
> So, based on that I would suggest going the OpenSearch approach and also suggest that STAC do the same.

**Comment by cholmes** [comment]
Ugh, there's a mailing list I'm supposed to be on to see updates? Why can't OGC just use github...

**Comment by m-mohr** [comment]
That is the SWG mailing list, but not sure why those updates were only communicated there and not in the respective issues.

**Comment by matthewhanson** [comment]
The ':' will indeed be problematic and I don't think we should align if they stick with that. 

On the other hand, I'd really like to align with OGC API, but this seems to be getting harder as time goes on. Might it help to organize a small virtual sprint to work out some of these issues. The problems I have is I don't have access to a lot of the work since I'm not an OGC member, and I can't figure out how to navigate the open repos on github, some sections seem out of date with others.

**Comment by philvarner** [comment]
It looks like from the discussion in https://github.com/opengeospatial/ogcapi-records/issues/22 that they decided to align with us on +/-  -- is there anything else to do on this issue?

**Comment by philvarner** [comment]
OGC aligned with us, so no work do do here.
