### ISSUE TITLE
FIlter on media types (and complex objects)

### ISSUE THREAD

**Issue by p1d1d1** [radiantearth/stac-api-spec#24]
Dear all, how to deal with images available in different media types? As I understand the spec, if I have an image available in let's say two media types I create an Item and put each media type in the Asset Object, is that correct?
If yes how can one filter on media types? The media type is an attribute on an Asset Object, while the "finest" granularity of the STAC API is the Item.  
Or should I organize my resources differently?

**Comment by m-mohr** [comment]
@p1d1d1 I moved this to stac-api-spec as this is basically an API spec issue, not a core spec issue. Indeed, the API is currently missing filters on complex objects, but we are aware of the problems (same thing applies for eo:bands an other complex objects) and would like to solve them in the future. It's good to see this use-case so that we can consider it when working on an API extension. At the moment there's unfortunately no good way or a best practice for this.

**Comment by p1d1d1** [comment]
ok thanks

**Comment by matthewhanson** [comment]
This sort of filtering will be handled by using CQL in the future ( #32 ), so closing this in favor of adopting that spec which can handle filtering of complex objects.
