### ISSUE TITLE
/search endpoint and link with rel="search" allowed in any subcatalog, not only in "root" ?

### ISSUE THREAD

**Issue by ycespb** [radiantearth/stac-api-spec#294]
It is not clear from reading the various parts of the specifications whether a link with rel="search" (indicating the capability of an API Item Search) can only appear in the "root catalog" (i.e. landing page) or in any (sub)catalog object.  The explanation of the "conformsTo" property suggests that some catalogs may support Item search (when the data is in a single database) while others may not, allowing the conformsTo array to be different in subcatalogs.  Does that mean that subcatalogs in a tree-structure can have their own dedicated "/search" endpoint indicated with rel="search" in their description ?  This then also means that the endpoint is not necessarily called "/search" which seems imposed in the spec  (but any path is allowed?)  or is the "/search" path relative to the path of the subcatalog/collection and not to the landing page (root), or is there a single /search endpoint and only the catalogues with corresponding "conformsTo" property are related to the unique /search endpoint ?

**Comment by philvarner** [comment]
The rel=search link can appear in any "sub" catalog object, but only if that object is itself a landing page. 

"subcatalogs" may have their own dedicated search endpoint, where invoking it restricts results only to that catalog.

The endpoint `/search` is relative to the root/landing page, rather than absolute. For example, E84 Earth Search is `https://earth-search.aws.element84.com/v0/search` and MS Planetary Computer is `https://planetarycomputer.microsoft.com/api/stac/v1/search`. So a "sub" catalog's url of something like `/catalogs/my_catalog/catalogs/my_subcatalog/search would be accetable.

Relatedly, it was perhaps a mistake to require that the endpoint be named `/search`, when all that matters is that there's *some* url accessible via the rel=search link relation. But, OAFeat usually uses fixed endpoint paths rather than arbitrary ones via link relation and OpenAPI specification is easier, so it's what we have.

**Comment by ycespb** [comment]
Thanks (that paths are relative to a landing page was already clear from reading the various specifications, where rel="search" may appear is not really clear in the specifications according to me).   (1) What then determines whether an object is a "landing page" or not ?  Is an object still a "landing page" (or "root catalog) when itself contains a link "rel=root" pointing to a different object and not to itself.  (2) In my understanding "landing page" and "root catalog" were synonyms in "STAC documentation" ?  (3)  I assume there is then no interdiction that a (or "the") "root catalog" has a "/search" endpoint and one of its child catalogs (assuming it is itself a "landing page" as per above) also declares a (different) "/search" endpoint and clients can use either of them for items in the child catalog ?

**Comment by philvarner** [comment]
> What then determines whether an object is a "landing page" or not ? 

It is a Catalog (type=Catalog and has required fields) and advertises the `STAC API - Core` conformance class URI in `conformsTo`

> Is an object still a "landing page" (or "root catalog) when itself contains a link "rel=root" pointing to a different object and not to itself.

Yes. Over time, I think we've changed how we think about this, and "landing page" and "root catalog" are now confusing. They are synonyms, but "root" is misleading, as it may not be the "ultimate" root that the `root` rel links to.

> (3) I assume there is then no interdiction that a (or "the") "root catalog" has a "/search" endpoint and one of its child catalogs (assuming it is itself a "landing page" as per above) also declares a (different) "/search"

I don't think that's a problem. I would not expect a child catalog to declare a search endpoint at all unless it were different from the parent catalog.
