### ISSUE TITLE
Define top-level queryables endpoint for Filter Extension

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#300]
OAFeat Part 3 does not define a top-level queryables endpoint, only ones per-collection. To support cross-collection search, a "global" queryables definition is needed. Per discussion in comments, this will be a user-defined subset of the intersection of all Item fields in all Collections.

Discussion in comments.

Original issue:

We recently discussed this during the cloud-native event 22, but want to quickly also raise them here officially. 
Background: STAC Browser tries to generate a web UI to search STAC APIs. I'm looking at the MS PC queryables implementation: https://planetarycomputer-staging.microsoft.com/api/stac/v1/queryables (+ for each collection)

1. $ref - There should be a way to retrieve the queryables without "external" references so that a browser-based client doesn't need to requests dozens of documents to build the full queryables schema. Either by default or with a query parameter (maybe something for OGC).
2. root queryables - The root queryables only lists the id as potential field to query on. Still, you can basically query on the union of queryables. This is confusing. I assume you should be able to retrieve the union of queryables, not just the intersection.

Thoughts?

cc @philvarner @rowanwins @pvretano

**Comment by philvarner** [comment]
1. Completely agree about the $refs -- we should recommend folks generate the schema with everything resolved.

2. I think the root is supposed to be the intersection -- everything that can be queried on and guarantee that all items will actually be evaluated. In this case, it should at least be all the required STAC Item fields, instead of only `id`. additionalProperties=true means you *can try* to query on other queryables, but you may not get the results you expect. 

That is a good point about the union vs. intersection. For example, it would be nice at the root to advertise that I have multiple collections that can be queried for cloud cover with the queryable "cloud_cover" (so the client knows it's that and not `properties.eo:cloud_cover` or `eo:cloud_cover`), but that not *all* items have that field, so I know that items without it will never be in the results.

**Comment by m-mohr** [comment]
I think I'd not agree with 2. Why would you only expose the intersection, but allow to query globally on more than what is exposed? Also, it doesn't help with generating UIs. And if I need to get all queryable from 100s of collections with 100s of HTTP requests, that's unusable.

**Comment by philvarner** [comment]
When I said "I think", I meant that's how it's defined in OAFeat Part 3. I recognize that it's problematic, and also think we need to figure out something that works better when heterogeneous, cross-collection query is default as in STAC API, rather than collection-specific query as in OAFeat. 

One possibility would be to change the semantics so that all of the fields listed in the schema are the union of terms, but then the JSON Schema `required` array defines the intersection within this union.

Also, the root wouldn't necessarily have to be the union of *all* terms, since there may be hundreds or thousands that are allowed in a catalog, but is more like a possibly curated group of the terms that are common or that generally make sense to query an entire catalog with. I don't know how fuzzy required should be -- must all items have those fields, or just most items, or just something that users commonly query with?

**Comment by pvretano** [comment]
Hmm ... @philvarner I just checked part three and I see one reference to a top-level `/queryables` but no discussion in the specification about it.  I remembering includes a top level `/queryables` in the original draft but we may have decided to remove it.  I created an [issue](https://github.com/opengeospatial/ogcapi-features/issues/688) about it to investigate.  Not sure if that helps (since you are free to define as you like) or hinders.

**Comment by philvarner** [comment]
Okay, great. It may not have actually been defined anywhere, and I misinterpreted what was there.

I think our best course of action is to define a top-level one that's effectively the intersection (not strictly mathematically, but more "a bunch of terms that you can write queries with that will return some results").  Probably no need for the additional semantics on required. What do you think @m-mohr ?

**Comment by m-mohr** [comment]
I just need something useful so that a UI can generate a reasonable interface. Ideally, this would be the union because it is meant to expose what you can query on. If you can query on the union, then this should IMHO be exposed. But at least is should be a curated list a provider expects to be used frequently, which is usually larger than the simple intersection (e.g. think about eo:cloud_cover if you host S1 and S2).

The required field seems semantically wrong because I'd understand it without further context as "you need to provide these fields to be present in your query to get results".

**Comment by philvarner** [comment]
closing, replaced by https://github.com/stac-api-extensions/filter/issues/1
