### ISSUE TITLE
ItemCollection: no version, extensions etc.

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-api-spec#400]
It looks like the ItemCollection is unversioned and doesn't allow extension through stac_extensions, right? Is this intentional?

Also, the readme of the fragment points to the SFS:
> In addition to STAC API extensions, the STAC [Single File STAC Extension](https://github.com/stac-extensions/single-file-stac/blob/main/README.md) provides a set of Collection and Item objects as a single file catalog.

SFS has been deprecated, so we should probably remove the paragraph.

**Comment by philvarner** [comment]
By "unversioned", you mean that it doesn't have a `stac_version` field? I think that's true because it's not a STAC entity, but something specific to STAC API.

As it now, I would say that it cannot be extended through stac_extensions since it's not a STAC entity. 

But, I think maybe ItemCollection should be defined in a STAC extension, and STAC API relies on it. This would be the first time we've defined a STAC extension that was an entity rather than just adding fields to the existing STAC entities, so there may be some problems there. (I wish we'd just have defined ItemCollection in core STAC even if it wasn't used in the Catalog-Collection-Item hierarchies).

**Comment by philvarner** [comment]
I do think it could be extended through a stac_api_extension since it's used by those conformance classes.

**Comment by m-mohr** [comment]
That's a good point, the ItemCollection could implicity be extended through the conformance classes.

Context: I was coming from a "migration" perspective, e.g. how stac-migrate could make sure the ItemCollection is always on the latest version and how to detect what version the current JSON is.
