### ISSUE TITLE
best practices for mixing STAC with non-STAC Collections

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#78]
We should have recommendations for how people combine STAC with non-STAC data in a single landing page, with some collections being STAC and some just Features, and how clients should deal with that. Latest [discussion](https://github.com/radiantearth/stac-api-spec/issues/70#issuecomment-738886427) recommends clients just look for stac_version in responses.

**Comment by philvarner** [comment]
Mixing STAC and non-STAC items seems tricky, since the clients must then constantly check the entities to validate that they're STAC.  It seems like the ability to mix STAC and non-STAC objects implies:

- `/collections` could return non-STAC Collections (e.g., also return OAFeat Collections), and a STAC client needs to check each one for `stac_version` to see which type it is?
- `/search` or `/collections/{cid}/items` could return Features instead of Items, and the client needs to check?
- `child` links from the root could be either to STAC Collections or OAF Collections, and the client needs to check?

**Comment by philvarner** [comment]
Moved:

- https://github.com/stac-api-extensions/best-practices/issues/1
