### ISSUE TITLE
Add CRS extension

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-api-spec#85]
We should add CRS as an extension, since it's the most mature OAFeat extension - https://portal.ogc.org/files/91976

 Could just scope it to ogcapi-features and just add it in extensions.md. Or could also add it to item-search.

**Comment by m-mohr** [comment]
Does it need changes to work for us? Otherwise we may not even need to "fully" add it and people can just use it from Features and then we could just add a note or so.

**Comment by cholmes** [comment]
I don't think it needs changes. And yeah, was thinking/hoping we could just add a note. But need to investigate how it is written and how it fits with our extension declaration stuff, especially if we wanted people to use it with search. But first thought was just add a note.

**Comment by philvarner** [comment]
(These are more notes for me rather than a full suggestion)

We should consider nominal support for this by advertising that the CRS is always WGS84 / 4326, and maybe just as part of our core rather than an extension. 

In the JSON representation of the collection (`/collections/{collectionId}`) the `crs` member is an array of supported CRSs. 

[relevant section in Part 2](https://docs.opengeospatial.org/is/18-058/18-058.html#_crs_identifier_list).

cportele said: We should also point out that, if there is no `crs` member, only the default is supported and the `filter-crs` parameter has no use. This is implied in the condition in requirement 8, but we should be more explicit in the informative text.

**Comment by philvarner** [comment]
Moved:

- https://github.com/stac-api-extensions/incubator/issues/2
